inputs:
  docker_build_context_path:
    required: true
  dockerfile_path:
    required: true
  environment:
    required: true
  github_personal_access_token:
    required: true
  github_username:
    required: true
  image_tag_1:
    required: true
  image_tag_2:
    required: true

runs:
  using: composite
  steps:
  - shell: bash
    run: |
      echo ${{ inputs.github_personal_access_token }} | docker login ghcr.io -u ${{ inputs.github_username }} --password-stdin
      image_tag_1='${{ inputs.image_tag_1 }}'
      image_tag_2='${{ inputs.image_tag_2 }}'
      if [ '${{ inputs.environment }}' == 'dev' ]; then
        sed -i 's/\(FROM ghcr\.io\/itopia-inc\/spaces-base-images\/.*\)$/\1-dev/g' ${{ inputs.dockerfile_path }}
        image_tag_1="$image_tag_1-dev"
        image_tag_2="$image_tag_2-dev"
      fi
      docker build -f ${{ inputs.dockerfile_path }} -t $image_tag_1 .
      build_status=$?
      if [ $build_status -eq 0 ]; then
          docker push $image_tag_1
          if [ $image_tag_2 != '' ]; then
            docker tag $image_tag_1 $image_tag_2
            docker push $image_tag_2
          fi
      else 
          echo "Docker build failed for tag: $image_tag_1"
      fi