name: Build & publish changed images

on:
  pull_request_target:
    branches:
    - main

jobs:

  detect_image_source_changes:
    runs-on: ubuntu-latest
    outputs:
      node_node-12-on-ubuntu-focal_changed: ${{ steps.changes_to_node_node-12-on-ubuntu-focal.outputs.any_changed }}
      node_node-14-on-ubuntu-focal_changed: ${{ steps.changes_to_node_node-14-on-ubuntu-focal.outputs.any_changed }}
      node_node-16-on-ubuntu-focal_changed: ${{ steps.changes_to_node_node-16-on-ubuntu-focal.outputs.any_changed }}
    steps:
    - id: changes_to_node_node-12-on-ubuntu-focal
      uses: tj-actions/changed-files@v1.1.2
      with:
        path: node/node-12-on-ubuntu-focal
    - id: changes_to_node_node-14-on-ubuntu-focal
      uses: tj-actions/changed-files@v1.1.2
      with:
        path: node/node-14-on-ubuntu-focal
    - id: changes_to_node_node-16-on-ubuntu-focal
      uses: tj-actions/changed-files@v1.1.2
      with:
        path: node/node-16-on-ubuntu-focal

  build_and_publish_node_node-12-on-ubuntu-focal:
    if: jobs.detect_image_source_changes.outputs.node_node-12-on-ubuntu-focal_changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, tag, and push
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build \
            -t ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:20.04-12 \
            node/node-12-on-ubuntu-focal
          docker push \
            ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:20.04-12
          docker tag \
            ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:20.04-12 \
            ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:focal-12
          docker push \
            ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:focal-12

  build_and_publish_others:
    runs-on: ubuntu-latest
    steps:
      - name: Build & publish spaces-ubuntu-node:20.04-14
        if: contains(steps.changed-files.outputs.modified_files, 'node/node-14-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: node/node-14-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:20.04-14
          push: true

      - name: Build & publish spaces-ubuntu-node:focal-14
        if: contains(steps.changed-files.outputs.modified_files, 'node/node-14-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: node/node-14-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:focal-14
          push: true

      - name: Build & publish spaces-ubuntu-node:20.04-16
        if: contains(steps.changed-files.outputs.modified_files, 'node/node-16-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: node/node-16-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:20.04-16
          push: true

      - name: Build & publish spaces-ubuntu-node:focal-16
        if: contains(steps.changed-files.outputs.modified_files, 'node/node-16-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: node/node-16-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-node:focal-16
          push: true

      - name: Build & publish spaces-ubuntu-openjdk:20.04-8
        if: contains(steps.changed-files.outputs.modified_files, 'openjdk/openjdk-8-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: openjdk/openjdk-8-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-openjdk:20.04-8
          push: true

      - name: Build & publish spaces-ubuntu-openjdk:focal-8
        if: contains(steps.changed-files.outputs.modified_files, 'openjdk/openjdk-8-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: openjdk/openjdk-8-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-openjdk:focal-8
          push: true

      - name: Build & publish spaces-ubuntu-openjdk:20.04-11
        if: contains(steps.changed-files.outputs.modified_files, 'openjdk/openjdk-11-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: openjdk/openjdk-11-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-openjdk:20.04-11
          push: true

      - name: Build & publish spaces-ubuntu-openjdk:focal-11
        if: contains(steps.changed-files.outputs.modified_files, 'openjdk/openjdk-11-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: openjdk/openjdk-11-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-openjdk:focal-11
          push: true

      - name: Build & publish spaces-ubuntu-python:20.04-2.7
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-2.7-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-2.7-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:20.04-2.7
          push: true

      - name: Build & publish spaces-ubuntu-python:focal-2.7
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-2.7-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-2.7-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:focal-2.7
          push: true

      - name: Build & publish spaces-ubuntu-python:20.04-3.6
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-3.6-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.6-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:20.04-3.6
          push: true

      - name: Build & publish spaces-ubuntu-python:focal-3.6
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-3.6-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.6-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:focal-3.6
          push: true

      - name: Build & publish spaces-ubuntu-python:20.04-3.7
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-3.7-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.7-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:20.04-3.7
          push: true

      - name: Build & publish spaces-ubuntu-python:focal-3.7
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-3.7-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.7-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:focal-3.7
          push: true

      - name: Build & publish spaces-ubuntu-python:20.04-3.8
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-3.8-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.8-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:20.04-3.8
          push: true

      - name: Build & publish spaces-ubuntu-python:focal-3.8
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-3.8-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.8-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:focal-3.8
          push: true

      - name: Build & publish spaces-ubuntu-python:20.04-3.9
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-3.9-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.9-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:20.04-3.9
          push: true

      - name: Build & publish spaces-ubuntu-python:focal-3.9
        if: contains(steps.changed-files.outputs.modified_files, 'python/python-3.9-on-ubuntu-focal/Dockerfile')
        uses: docker/build-push-action@v2
        with:
          context: python/python-3.9-on-ubuntu-focal
          tags: ghcr.io/itopia-inc/spaces-images/spaces-ubuntu-python:focal-3.9
          push: true
