name: 'Trigger: Automation change'

on:
  push:
    branches:
    - main
    paths:
    - '.github/actions/build-image/action.yaml'
    - '.github/workflows/build_all_images.yaml'
    - '.github/workflows/build_changed_images.yaml'
    - '.github/workflows/on_automation_change.yaml'
    - '.github/workflows/on_source_change.yaml'

jobs:

  publish_all_dev:
    uses: itopia-inc/spaces-images/.github/workflows/build_all_images.yaml@main
    with:
      environment: "dev"
