name: 'Trigger: Automation change'

on:
  push:
    branches:
    - main
    paths:
    - '.github/**'

jobs:

  publish_all_dev:
    uses: itopia-inc/spaces-images/.github/workflows/build_all_images.yaml@main
    with:
      environment: "dev"
