name: 'Trigger: PR with workflow change'

on:
  pull_request:
    branches:
    - main
    paths:
    - '.github/**'

jobs:

  build_all_dev:
    uses: itopia-inc/spaces-images/.github/workflows/build_all_images.yaml@main
    with:
      environment: "dev"
