name: 'Trigger: PR with workflow change'

on:
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/build_all_images.yaml'
    - '.github/workflows/build_changed_images.yaml'
    - '.github/workflows/on_pr_with_automation_change.yaml'
    - '.github/workflows/on_pr_with_source_change.yaml'

jobs:

  build_all_dev:
    uses: itopia-inc/spaces-images/.github/workflows/build_all_images.yaml@main
    with:
      environment: "dev"
